GET http://localhost:5000/home
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhbmgiLCJpYXQiOjE2NTg4MTUyNjAsImV4cCI6MTY1ODgxNTMyMH0._Ts1CrZzBYgxZo30QRv3unoLiBAlXGN8VC2u8RfOfqc

###
POST http://localhost:5000/author/login
Content-Type: application/json

{
    "username": "vanh"
}